name: Build All

on:
  push:
    branches-ignore:
      - publish-docs

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - { binary-version: "2.12", java-version: "11", java-distribution: "temurin" }

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-java@v4.7.0
      with:
        java-version: ${{ matrix.scala.java-version }}
        distribution: ${{ matrix.scala.java-distribution }}
        cache: 'sbt'
    - uses: sbt/setup-sbt@v1

    - name: Build
      run: |
        java -version
        .github/workflows/sbt-build-simple.sh
