name: "[Doc][A] Build Only"

on:
  push:
    branches:
      - "**"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - { version: "2.13.10", binary-version: "2.13", java-version: "11", java-distribution: "temurin" }
        node:
          - { version: "22.19.0" }

    steps:
      - uses: actions/checkout@v5.0.0
      - uses: actions/setup-java@v4.7.0
        with:
          java-version: ${{ matrix.scala.java-version }}
          distribution: ${{ matrix.scala.java-distribution }}
          cache: 'sbt'
      - uses: sbt/setup-sbt@v1

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node.version }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          cache-dependency-path: 'website/package-lock.json'

      - name: Build website
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
          GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
          GA_ANONYMIZE_IP: ${{ secrets.GA_ANONYMIZE_IP }}
        run: |
          rm website/package-lock.json
          sbt clean \
            docusaurGenerateAlgoliaConfigFile \
            docusaurGenerateGoogleAnalyticsConfigFile \
            docusaurInstall \
            docusaurCleanBuild \
            docusaurBuild
